# Generated by Django 4.2.9 on 2024-01-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
