# Generated by Django 4.2.9 on 2024-01-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='assigned_date',
        ),
    ]
